name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.50.0
    steps:
      - uses: actions/checkout@v4

      - name: Check Maven repository path
        run: ls -la /root/.m2/repository || echo "Repository not found"

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: |
          export DISPLAY=:0
          Xvfb :0 -screen 0 1920x1080x24 >/dev/null 2>&1 &  
          mvn test -B

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/